#ifndef INTERFACE_DATA
#define INTERFACE_DATA

// PALETTE ID
#define OBJ_PALETTE_UI_ID 0

// OAM ID
// ======
#define OAM_AXES_LABEL 0
#define OAM_AXES_ROLL_CURSOR 1
#define OAM_AXES_PITCH_CURSOR 2
#define OAM_AXES_YAW_CURSOR 3

// TILE ID
// =======
#define TILE_AXES_LABEL 0
#define TILE_AXES_ROLL_CURSOR 0
#define TILE_AXES_PITCH_CURSOR 0
#define TILE_AXES_YAW_CURSOR 0

#endif
