/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t title_tiles[];
extern const uint8_t title_tiles_end[];
#if __cplusplus >= 201103L
static constexpr size_t title_tiles_size=19200;
#else
static const size_t title_tiles_size=19200;
#endif
