/* Generated by BIN2S - please don't edit directly */
	.section .rodata.title_obj_palette, "a"
	.balign 4
	.global title_obj_palette
title_obj_palette:
	.byte   0,  0,255,127,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
	.byte   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0

	.global title_obj_palette_end
title_obj_palette_end:

