/* Generated by BIN2S - please don't edit directly */
	.section .rodata.title_palette, "a"
	.balign 4
	.global title_palette
title_palette:
	.byte   0,  0,  0,  0,162, 48,179,110, 71, 81,255,127,129, 56,194, 84
	.byte 164, 90,131,115, 35,103, 87,107, 56,  4

	.global title_palette_end
title_palette_end:

