/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t axes_png[];
extern const uint8_t axes_png_end[];
#if __cplusplus >= 201103L
static constexpr size_t axes_png_size=382;
#else
static const size_t axes_png_size=382;
#endif
