/* Generated by BIN2S - please don't edit directly */
	.section .rodata.caret_tiles, "a"
	.balign 4
	.global caret_tiles
caret_tiles:
	.byte  17,  1,  0,  0, 97,  1,  0,  0, 97,  1,  0,  0, 97,  1,  0,  0
	.byte  17,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0

	.global caret_tiles_end
caret_tiles_end:

