/* Generated by BIN2S - please don't edit directly */
	.section .rodata.facecam_normal_bottom_tiles, "a"
	.balign 4
	.global facecam_normal_bottom_tiles
facecam_normal_bottom_tiles:
	.byte  49, 51, 51, 19, 51, 51, 51, 51, 17, 51, 51, 51, 51, 51, 49, 51
	.byte  51, 51, 19, 17, 49, 51, 51, 51, 18, 17, 17, 17, 33, 34, 34, 34
	.byte  51, 51, 51, 17, 51, 51, 51, 19, 51, 51, 19, 17, 51, 49, 51, 19
	.byte  17, 51, 51, 19, 51, 51, 51, 33, 17, 17, 17, 34, 34, 34, 34, 17

	.global facecam_normal_bottom_tiles_end
facecam_normal_bottom_tiles_end:

