/* Generated by BIN2S - please don't edit directly */
	.section .rodata.facecam_sick_top_tiles, "a"
	.balign 4
	.global facecam_sick_top_tiles
facecam_sick_top_tiles:
	.byte  49, 19, 17, 17, 49, 51, 17, 17, 21, 51, 19, 17, 21, 51, 51, 67
	.byte  51, 19, 49, 51, 51, 17, 18, 51, 51, 17, 17, 51, 51, 19, 49, 51
	.byte  17, 17, 68, 33, 17, 65, 68, 17, 17, 68, 20, 85, 68, 68, 20, 85
	.byte  68, 17, 68, 68, 19, 33, 65, 20, 19, 17, 49, 20, 51, 17, 51, 19

	.global facecam_sick_top_tiles_end
facecam_sick_top_tiles_end:

