/* Generated by BIN2S - please don't edit directly */
	.section .rodata.facecam_sick_bottom_tiles, "a"
	.balign 4
	.global facecam_sick_bottom_tiles
facecam_sick_bottom_tiles:
	.byte  49, 51, 51, 51, 17, 49, 51, 51, 49, 51, 19, 51, 49, 51, 51, 17
	.byte  18, 51, 51, 51, 34, 17, 17, 17, 17, 34, 34, 34,  0, 17, 33, 34
	.byte  51, 51, 51, 51, 51, 51, 51, 17, 19, 49, 51, 51, 49, 19, 51, 51
	.byte  51, 51, 51, 19, 17, 17, 17, 33, 34, 34, 34, 18, 34, 34, 17,  1

	.global facecam_sick_bottom_tiles_end
facecam_sick_bottom_tiles_end:

