/* Generated by BIN2S - please don't edit directly */
	.section .rodata.facecam_name_3_tiles, "a"
	.balign 4
	.global facecam_name_3_tiles
facecam_name_3_tiles:
	.byte   0,  0,  0,  0, 17, 17, 17, 17, 33, 34, 34, 33, 33, 17, 17, 33
	.byte  33, 34,  1, 33, 33, 17, 17, 33, 33, 34, 34, 33, 17, 17, 17, 17
	.byte   0,  0,  0,  0, 17, 17, 17,  1, 34, 18, 33,  1, 17, 33, 33, 17
	.byte   1, 33, 33, 33, 17, 33, 33, 33, 34, 18, 33, 34, 17, 17, 17, 17
	.byte   0,  0,  0,  0, 17, 17, 17, 17, 33, 33, 34, 34, 33, 17, 33, 17
	.byte  33,  1, 33,  1, 33, 17, 33, 17, 34, 33, 34, 34, 17, 17, 17, 17
	.byte   0,  0,  0,  0, 17,  1, 17,  1, 33,  1, 33,  1, 33, 18, 33,  1
	.byte  33, 33, 33,  1, 33, 17, 34,  1, 33,  1, 33,  1, 17,  1, 16,  1

	.global facecam_name_3_tiles_end
facecam_name_3_tiles_end:

