/* Generated by BIN2S - please don't edit directly */
	.section .rodata.facecam_0_palette, "a"
	.balign 4
	.global facecam_0_palette
facecam_0_palette:
	.byte   0,  0,  0,  0,255,127, 29, 79,248, 37,221,118, 75, 41

	.global facecam_0_palette_end
facecam_0_palette_end:

