/* Generated by BIN2S - please don't edit directly */
	.section .rodata.facecam_name_1_tiles, "a"
	.balign 4
	.global facecam_name_1_tiles
facecam_name_1_tiles:
	.byte   0,  0,  0,  0,  0, 16, 17, 16,  0, 16, 18, 16,  0, 16, 34, 17
	.byte   0, 16, 18, 18,  0, 16, 18, 33,  0, 16, 18, 16,  0, 16, 17,  0
	.byte   0,  0,  0,  0, 17, 17, 17, 17, 18, 34, 34, 18, 18, 18, 17, 17
	.byte  18, 34, 18,  0, 18, 18, 17, 17, 18, 34, 34, 18, 17, 17, 17, 17
	.byte   0,  0,  0,  0, 17, 17, 17, 17, 34, 34, 18, 18, 17, 18, 16, 18
	.byte  16, 18, 16, 18, 17, 18, 17, 18, 34, 34, 18, 34, 17, 17, 17, 17
	.byte   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
	.byte   0,  0,  0,  0, 17, 17,  0,  0, 34, 18,  0,  0, 17, 17,  0,  0

	.global facecam_name_1_tiles_end
facecam_name_1_tiles_end:

