/* Generated by BIN2S - please don't edit directly */
	.section .rodata.facecam_1_palette, "a"
	.balign 4
	.global facecam_1_palette
facecam_1_palette:
	.byte   0,  0,  0,  0,255,127,248, 37,248, 37,221,118, 75, 41

	.global facecam_1_palette_end
facecam_1_palette_end:

