/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t facecam_sick_top_tiles[];
extern const uint8_t facecam_sick_top_tiles_end[];
#if __cplusplus >= 201103L
static constexpr size_t facecam_sick_top_tiles_size=64;
#else
static const size_t facecam_sick_top_tiles_size=64;
#endif
