/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t interface_palette_1_png[];
extern const uint8_t interface_palette_1_png_end[];
#if __cplusplus >= 201103L
static constexpr size_t interface_palette_1_png_size=125;
#else
static const size_t interface_palette_1_png_size=125;
#endif
