/* Generated by BIN2S - please don't edit directly */
	.section .rodata.interface_0_palette, "a"
	.balign 4
	.global interface_0_palette
interface_0_palette:
	.byte  31,124,  0,  0,255,127,224,  3,191,  1, 75, 41, 31,  0

	.global interface_0_palette_end
interface_0_palette_end:

