/* Generated by BIN2S - please don't edit directly */
	.section .rodata.interface_palette_1_png, "a"
	.balign 4
	.global interface_palette_1_png
interface_palette_1_png:
	.byte 137, 80, 78, 71, 13, 10, 26, 10,  0,  0,  0, 13, 73, 72, 68, 82
	.byte   0,  0,  0,  7,  0,  0,  0,  1,  8,  3,  0,  0,  0, 37,213, 68
	.byte 252,  0,  0,  0,  1,115, 82, 71, 66,  0,174,206, 28,233,  0,  0
	.byte   0, 27, 80, 76, 84, 69,255,  0,255,  0,  0,  0,255,255,255,  0
	.byte 255,  0,255,111,  0, 89, 86, 82,255,  0,  0,  0,247,255,  0,195
	.byte 255,155,255, 28,252,  0,  0,  0, 16, 73, 68, 65, 84,  8,153, 99
	.byte  96, 96,100, 98,229, 96,101,  6,  0,  0, 81,  0, 25, 64, 63,232
	.byte 226,  0,  0,  0,  0, 73, 69, 78, 68,174, 66, 96,130

	.global interface_palette_1_png_end
interface_palette_1_png_end:

