/* Generated by BIN2S - please don't edit directly */
	.section .rodata.interface_1_palette, "a"
	.balign 4
	.global interface_1_palette
interface_1_palette:
	.byte   0,  0,  0,  0, 75, 41,255,127,224,  3,224,126, 31,124,  0,  0
	.byte   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0

	.global interface_1_palette_end
interface_1_palette_end:

