/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t interface_palette[];
extern const uint8_t interface_palette_end[];
#if __cplusplus >= 201103L
static constexpr size_t interface_palette_size=14;
#else
static const size_t interface_palette_size=14;
#endif
