/* Generated by BIN2S - please don't edit directly */
	.section .rodata.interface_1_palette, "a"
	.balign 4
	.global interface_1_palette
interface_1_palette:
	.byte  31,124,  0,  0,255,127, 31,  0, 64,127, 75, 41,224,  3

	.global interface_1_palette_end
interface_1_palette_end:

