/* Generated by BIN2S - please don't edit directly */
	.section .rodata.interface_palette_0_png, "a"
	.balign 4
	.global interface_palette_0_png
interface_palette_0_png:
	.byte 137, 80, 78, 71, 13, 10, 26, 10,  0,  0,  0, 13, 73, 72, 68, 82
	.byte   0,  0,  0,  7,  0,  0,  0,  1,  8,  3,  0,  0,  0, 37,213, 68
	.byte 252,  0,  0,  0,  1,115, 82, 71, 66,  0,174,206, 28,233,  0,  0
	.byte   0, 21, 80, 76, 84, 69,255,  0,255,  0,  0,  0,255,255,255,  0
	.byte 255,  0,255,111,  0, 89, 86, 82,255,  0,  0,226,238,183, 95,  0
	.byte   0,  0, 16, 73, 68, 65, 84,  8,153, 99, 96, 96,100, 98,102, 97
	.byte 101,  3,  0,  0, 64,  0, 22, 14,219,145,147,  0,  0,  0,  0, 73
	.byte  69, 78, 68,174, 66, 96,130

	.global interface_palette_0_png_end
interface_palette_0_png_end:

