/* Generated by BIN2S - please don't edit directly */
	.section .rodata.interface_palette, "a"
	.balign 4
	.global interface_palette
interface_palette:
	.byte  31,124,  0,  0,255,127,131, 11,184, 21, 75, 41, 53,  0

	.global interface_palette_end
interface_palette_end:

