/* Generated by BIN2S - please don't edit directly */
	.section .rodata.label_palette_1_png, "a"
	.balign 4
	.global label_palette_1_png
label_palette_1_png:
	.byte 137, 80, 78, 71, 13, 10, 26, 10,  0,  0,  0, 13, 73, 72, 68, 82
	.byte   0,  0,  0,  2,  0,  0,  0,  1,  8,  6,  0,  0,  0,244, 34,127
	.byte 138,  0,  0,  0,  1,115, 82, 71, 66,  0,174,206, 28,233,  0,  0
	.byte   0, 17, 73, 68, 65, 84,  8,153, 99,100, 96, 96,248,255,255,255
	.byte 127,  6,  0, 14,  4,  3,254,247, 82,158,127,  0,  0,  0,  0, 73
	.byte  69, 78, 68,174, 66, 96,130

	.global label_palette_1_png_end
label_palette_1_png_end:

