/* Generated by BIN2S - please don't edit directly */
	.section .rodata.label_2_palette, "a"
	.balign 4
	.global label_2_palette
label_2_palette:
	.byte   0,  0,  0,  0,131, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
	.byte   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0

	.global label_2_palette_end
label_2_palette_end:

