/* Generated by BIN2S - please don't edit directly */
	.section .rodata.label_1_palette, "a"
	.balign 4
	.global label_1_palette
label_1_palette:
	.byte   0,  0,  0,  0,255,127,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
	.byte   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0

	.global label_1_palette_end
label_1_palette_end:

