/* Generated by BIN2S - please don't edit directly */
	.section .rodata.stage_gauge_tiles, "a"
	.balign 4
	.global stage_gauge_tiles
stage_gauge_tiles:
	.byte   0,  0,  0,  0, 17,  1, 16, 17, 33,  1, 16, 19, 33,  1, 16, 19
	.byte  33,  1, 16, 19, 33, 17, 17, 17, 33, 34, 34, 34, 17, 17, 17, 17
	.byte   0,  0,  0,  0,  0,  0, 16, 17,  0,  0, 16, 18,  0,  0, 16, 18
	.byte   0,  0, 16, 18, 17, 17, 17, 18, 34, 34, 34, 18, 17, 17, 17, 17

	.global stage_gauge_tiles_end
stage_gauge_tiles_end:

