/* Generated by BIN2S - please don't edit directly */
	.section .rodata.stage_decoupler_h_tiles, "a"
	.balign 4
	.global stage_decoupler_h_tiles
stage_decoupler_h_tiles:
	.byte   0,  0,  0,  0,  0,  0,  0,  0, 16, 17, 17, 17, 16, 85, 85, 85
	.byte  16, 85, 85, 85, 16, 85, 85, 85, 16, 85, 37, 85, 16, 85, 37, 85
	.byte   0,  0,  0,  0,  0,  0,  0,  0, 17, 17, 17,  0, 85, 85, 21,  0
	.byte  85, 85, 21,  0, 85, 85, 21,  0, 37, 85, 21,  0, 37, 85, 21,  0
	.byte  16, 85, 37, 37, 16, 85, 37, 85, 16, 85, 37, 85, 16, 85, 85, 85
	.byte  16, 85, 85, 85, 16, 85, 85, 85, 16, 17, 17, 17,  0,  0,  0,  0
	.byte  37, 85, 21,  0, 37, 85, 21,  0, 37, 85, 21,  0, 85, 85, 21,  0
	.byte  85, 85, 21,  0, 85, 85, 21,  0, 17, 17, 17,  0,  0,  0,  0,  0

	.global stage_decoupler_h_tiles_end
stage_decoupler_h_tiles_end:

