/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t stage_separator_tiles[];
extern const uint8_t stage_separator_tiles_end[];
#if __cplusplus >= 201103L
static constexpr size_t stage_separator_tiles_size=96;
#else
static const size_t stage_separator_tiles_size=96;
#endif
