/* Generated by BIN2S - please don't edit directly */
	.section .rodata.stage_separator_tiles, "a"
	.balign 4
	.global stage_separator_tiles
stage_separator_tiles:
	.byte   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 16, 17
	.byte  16, 17, 16, 68, 16, 18, 16, 68, 16, 17, 16, 17,  0,  0,  0,  0
	.byte   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 17, 17, 17, 17
	.byte  68, 68, 68, 68, 68, 68, 68, 68, 17, 17, 17, 17,  0,  0,  0,  0
	.byte   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 17, 17, 17, 17
	.byte  68, 68, 68, 20, 68, 68, 68, 20, 17, 17, 17, 17,  0,  0,  0,  0

	.global stage_separator_tiles_end
stage_separator_tiles_end:

