/* Generated by BIN2S - please don't edit directly */
	.section .rodata.stage_separator_png, "a"
	.balign 4
	.global stage_separator_png
stage_separator_png:
	.byte 137, 80, 78, 71, 13, 10, 26, 10,  0,  0,  0, 13, 73, 72, 68, 82
	.byte   0,  0,  0, 24,  0,  0,  0,  8,  8,  6,  0,  0,  0,227,161, 63
	.byte  99,  0,  0,  0,  1,115, 82, 71, 66,  0,174,206, 28,233,  0,  0
	.byte   0, 56, 73, 68, 65, 84, 40,145, 99, 96, 24,  5,  4,  0, 35, 14
	.byte 241,255,212,178,128,  5,139,129,140, 12, 12, 12, 12,255,243, 41
	.byte  55,156,113, 34,  3,  3, 19,140,243,255, 63,213, 28,141,106,  9
	.byte 204,124, 52, 49,218,216, 70, 11,  0,  0,174,249,  9,  4, 76, 56
	.byte 111, 71,  0,  0,  0,  0, 73, 69, 78, 68,174, 66, 96,130

	.global stage_separator_png_end
stage_separator_png_end:

