/* Generated by BIN2S - please don't edit directly */
	.section .rodata.stage_decoupler_h_icons_png, "a"
	.balign 4
	.global stage_decoupler_h_icons_png
stage_decoupler_h_icons_png:
	.byte 137, 80, 78, 71, 13, 10, 26, 10,  0,  0,  0, 13, 73, 72, 68, 82
	.byte   0,  0,  0, 16,  0,  0,  0, 16,  8,  6,  0,  0,  0, 31,243,255
	.byte  97,  0,  0,  0,  1,115, 82, 71, 66,  0,174,206, 28,233,  0,  0
	.byte   0, 76, 73, 68, 65, 84, 56,141, 99, 96, 24,104,192,  8,165,255
	.byte 147,171,151,  5,198,139, 12, 11, 34, 90,231,242, 85,235,224,108
	.byte  38, 50,108, 70,  1,180, 49, 96,217,202,181,120,249,180,119,  1
	.byte  49, 54, 19,101, 64, 84,120, 48,101,  6, 16,  3,224,  9,137,140
	.byte 116,192, 72, 21, 23, 80,207, 11, 20,232,165, 12,  0,  0, 91, 94
	.byte  16, 18,243,200,200,112,  0,  0,  0,  0, 73, 69, 78, 68,174, 66
	.byte  96,130

	.global stage_decoupler_h_icons_png_end
stage_decoupler_h_icons_png_end:

