/* Generated by BIN2S - please don't edit directly */
	.section .rodata.stage_engine_tiles, "a"
	.balign 4
	.global stage_engine_tiles
stage_engine_tiles:
	.byte   0,  0,  0,  0,  0,  0,  0,  0, 16, 17, 17, 17, 16, 85, 85, 85
	.byte  16, 85, 85, 85, 16, 85, 37, 34, 16, 85, 37, 34, 16, 85, 37, 34
	.byte   0,  0,  0,  0,  0,  0,  0,  0, 17, 17, 17,  0, 85, 85, 21,  0
	.byte  85, 85, 21,  0, 34, 85, 21,  0, 34, 85, 21,  0, 34, 85, 21,  0
	.byte  16, 85, 85, 34, 16, 85, 85, 37, 16, 85, 85, 34, 16, 85, 37, 34
	.byte  16, 85, 85, 85, 16, 85, 85, 85, 16, 17, 17, 17,  0,  0,  0,  0
	.byte  82, 85, 21,  0, 85, 85, 21,  0, 82, 85, 21,  0, 34, 85, 21,  0
	.byte  85, 85, 21,  0, 85, 85, 21,  0, 17, 17, 17,  0,  0,  0,  0,  0

	.global stage_engine_tiles_end
stage_engine_tiles_end:

