/* Generated by BIN2S - please don't edit directly */
	.section .rodata.stage_decoupler_v_icons_png, "a"
	.balign 4
	.global stage_decoupler_v_icons_png
stage_decoupler_v_icons_png:
	.byte 137, 80, 78, 71, 13, 10, 26, 10,  0,  0,  0, 13, 73, 72, 68, 82
	.byte   0,  0,  0, 16,  0,  0,  0, 16,  8,  6,  0,  0,  0, 31,243,255
	.byte  97,  0,  0,  0,  1,115, 82, 71, 66,  0,174,206, 28,233,  0,  0
	.byte   0, 77, 73, 68, 65, 84, 56,141, 99, 96, 24,104,192,  8,165,255
	.byte 147,171,151,  5,198,139, 12, 11, 34, 90,231,242, 85,235,224,108
	.byte  38, 50,108, 70,  1, 20, 27,192,130, 77,112,217,202,181, 24, 98
	.byte  81,225,193,196, 27,128, 75, 49, 54,128,215, 11,216, 92, 66,146
	.byte   1,196,184,100,144,135,  1, 93, 12,160, 56, 47, 80, 12,  0, 44
	.byte  90, 16, 43, 25,200, 43,201,  0,  0,  0,  0, 73, 69, 78, 68,174
	.byte  66, 96,130

	.global stage_decoupler_v_icons_png_end
stage_decoupler_v_icons_png_end:

