/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t start_2_tiles[];
extern const uint8_t start_2_tiles_end[];
#if __cplusplus >= 201103L
static constexpr size_t start_2_tiles_size=512;
#else
static const size_t start_2_tiles_size=512;
#endif
