/* Generated by BIN2S - please don't edit directly */
	.section .rodata.title_object_palette, "a"
	.balign 4
	.global title_object_palette
title_object_palette:
	.byte   0,  0,255,127, 56,  4

	.global title_object_palette_end
title_object_palette_end:

