/* Generated by BIN2S - please don't edit directly */
	.section .rodata.ui_palette, "a"
	.balign 4
	.global ui_palette
ui_palette:
	.byte  31,124,  0,  0, 75, 41,255,127, 53,  0,184, 21,131, 11,  0,  0
	.byte   0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0

	.global ui_palette_end
ui_palette_end:

